sudo apt-get install google-cloud-cli-anthos-auth
sudo apt-get install google-cloud-cli-app-engine-go
sudo apt-get install google-cloud-cli-app-engine-grpc
sudo apt-get install google-cloud-cli-app-engine-python
sudo apt-get install google-cloud-cli-app-engine-python-extras
sudo apt-get install oogle-cloud-cli-bigtable-emulator
sudo apt-get install google-cloud-cli-cbt
sudo apt-get install google-cloud-cli-cloud-build-local
sudo apt-get install google-cloud-cli-cloud-run-proxy
sudo apt-get install google-cloud-cli-config-connector
sudo apt-get install google-cloud-cli-datastore-emulator
sudo apt-get install google-cloud-cli-firestore-emulator
sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
sudo apt-get install google-cloud-cli-kpt
sudo apt-get install google-cloud-cli-kubectl-oidc
sudo apt-get install google-cloud-cli-app-engine-java
sudo apt-get install google-cloud-cli-local-extract
sudo apt-get install google-cloud-cli-minikube
sudo apt-get install google-cloud-cli-nomos
sudo apt-get install google-cloud-cli-pubsub-emulator
sudo apt-get install google-cloud-cli-skaffold
sudo apt-get install google-cloud-cli-spanner-emulator
sudo apt-get install google-cloud-cli-terraform-validator
sudo apt-get install google-cloud-cli-tests
sudo apt-get install kubectl